# Generated by Django 3.2.6 on 2021-08-16 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('stream', multiselectfield.db.fields.MultiSelectField(choices=[('Agriculture', 'Agriculture'), ('Arts & Humanities', 'Arts & Humanities'), ('Commerce & Banking', 'Commerce & Banking'), ('Dental', 'Dental'), ('Design', 'Design'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Hotel Management', 'Hotel Management'), ('Information Technology', 'Information Technology'), ('Law', 'Law'), ('Management', 'Management'), ('Mass Communication', 'Mass Communication'), ('Medical', 'Medical'), ('Nursing', 'Nursing'), ('Paramedical', 'Paramedical'), ('Performing Arts', 'Performing Arts'), ('Pharmacy', 'Pharmacy'), ('Sciences', 'Sciences')], max_length=220)),
                ('slug', models.SlugField(max_length=164, unique=True)),
                ('established_in', models.CharField(blank=True, max_length=4, null=True)),
                ('college_type', models.CharField(blank=True, max_length=32, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=32, null=True)),
                ('highest_placement', models.CharField(blank=True, max_length=16, null=True)),
                ('avg_placement', models.CharField(blank=True, max_length=16, null=True)),
                ('facilities', multiselectfield.db.fields.MultiSelectField(choices=[('Gym', 'Gym'), ('ATM', 'ATM'), ('Playground', 'Playground'), ('Hostel', 'Hostel'), ('Library', 'Library'), ('Transport', 'Transport'), ('Labs', 'Labs'), ('Canteen', 'Canteen'), ('Clinic', 'Clinic'), ('Computer Labs', 'Computer Labs')], max_length=77, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('college_overall_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('comment', models.TextField()),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='website.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Course')),
                ('type', models.CharField(blank=True, help_text='e.g. Under Graduate, Post Graduate, etc.', max_length=64, null=True)),
                ('mode', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time'), ('Distance Learning', 'Distance Learning')], max_length=37, null=True)),
                ('fees', models.CharField(blank=True, max_length=64, null=True)),
                ('duration', models.CharField(max_length=4)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='website.college')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, choices=[('10th', '10th'), ('12th', '12th'), ('UG', 'UG'), ('PG', 'PG'), ('Ph.D.', 'Ph.D.')], max_length=5, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=4, null=True)),
                ('university', models.CharField(blank=True, max_length=64, null=True)),
                ('score', models.CharField(blank=True, max_length=4, null=True)),
                ('stream', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Educational Details',
                'unique_together': {('user', 'degree')},
            },
        ),
    ]
