# Generated by Django 3.2.5 on 2021-08-01 15:07

from django.db import migrations


streams = [
    'Sciences',
    'Pharmacy',
    'Performing Arts',
    'Paramedical',
    'Nursing',
    'Medical',
    'Mass Communication',
    'Management',
    'Law',
    'Information Technology',
    'Hotel Management',
    'Engineering',
    'Education',
    'Design',
    'Dental',
    'Commerce & Banking',
    'Arts & Humanities',
    'Agriculture',
]

facilities = [
    "ATM",
    "Canteen",
    "Clinic",
    "Computer Lab",
    "Gym",
    "Hostel",
    "Labs",
    "Library",
    "Playing Ground",
    "Transport",
]


def initializeDB(apps, schema_editor):
    Stream = apps.get_model("website", "Stream")
    Facility = apps.get_model("website", "Facility")
    streamsList = []
    facilitiesList = []

    for stream in streams:
        streamsList.append(Stream(name=stream))

    for facility in facilities:
        facilitiesList.append(Facility(name=facility))

    Stream.objects.bulk_create(streamsList)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initializeDB),
    ]
