# Generated by Django 3.2.6 on 2021-08-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210816_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='facilities',
            field=models.ManyToManyField(to='website.Facility'),
        ),
    ]
