# Generated by Django 3.2.6 on 2021-08-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_college_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='facilities',
            field=models.ManyToManyField(null=True, to='website.Facility'),
        ),
    ]
