# Generated by Django 3.2.6 on 2021-08-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210822_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_ranking',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
