# Generated by Django 3.2.6 on 2021-08-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210823_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('college_name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
                ('message', models.TextField()),
            ],
        ),
    ]
