# Generated by Django 3.2.6 on 2021-08-27 06:06

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year', models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2022)])),
                ('exam_mode', multiselectfield.db.fields.MultiSelectField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=14)),
                ('application_start_date', models.DateField(blank=True, null=True)),
                ('application_end_date', models.DateField(blank=True, null=True)),
                ('exam_start_date', models.DateField(blank=True, null=True)),
                ('exam_end_date', models.DateField(blank=True, null=True)),
                ('information', models.TextField()),
                ('stream', models.ManyToManyField(to='website.Stream')),
            ],
        ),
    ]
