# Generated by Django 3.2.6 on 2021-08-27 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_examdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetail',
            name='year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
