# Generated by Django 3.2.6 on 2021-08-27 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20210827_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetail',
            name='exam_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
