# Generated by Django 3.2.6 on 2021-08-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_examdetail_exam_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examdetail',
            options={'ordering': ['-exam_year']},
        ),
    ]
