# Generated by Django 3.2.6 on 2021-08-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20210827_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetail',
            name='slug',
            field=models.SlugField(max_length=164, null=True, unique=True),
        ),
    ]
