# Generated by Django 3.2.7 on 2021-09-01 18:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_examdetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetail',
            name='information',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
